SELECT * FROM customer_behaviour;

--Q1) what is the total revenue generated by male vs female customers?

SELECT gender, sum(purchase_amount) AS total_revenue_generated
FROM customer_behaviour
GROUP BY 1;

--Q2) Which customers used a discount but still spend more than the average purchase amount ?

SELECT customer_id, purchase_amount
FROM customer_behaviour
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer_behaviour);

--Q3) Which are the top 5 products with the highest average review rating ?

SELECT item_purchased, ROUND(AVG(review_rating::numeric),2) AS avg_product_rating
FROM customer_behaviour
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5;

--Q4) Compare the average purchase amounts between standard and express shipping.

SELECT shipping_type, ROUND(AVG(purchase_amount::NUMERIC),2) AS Avg_purchase_amounts
FROM customer_behaviour
WHERE shipping_type in ('Standard','Express')
GROUP BY 1;

--Q5) Do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers.

SELECT subscription_status,COUNT(customer_id) AS no_of_customers, AVG(purchase_amount) AS avg_spend, SUM(purchase_amount) AS total_revenue
FROM customer_behaviour
GROUP BY 1
ORDER BY 4,3;

--Q6) which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased,ROUND(100 * SUM(CASE WHEN  discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS percentage_purchase_amount
FROM customer_behaviour
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5;

--Q7) Segment customers into new, returning and loyal based on their total number of pervious purchases, 
--and show the count of each segment.

--Purchases 1 time == New, in between 2-10times == returning and more than == loyal

SELECT SUM(CASE WHEN previous_purchases =1 THEN 1 ELSE 0 END) AS new_customer, 
		SUM(CASE WHEN previous_purchases BETWEEN 2 AND 10 THEN 1 ELSE 0 END) AS returning_customers,
		SUM(CASE WHEN previous_purchases > 10 THEN 1 ELSE 0 END) AS loyal_customers
FROM customer_behaviour;

-- using CTAS

CREATE TABLE customer_type AS
	(
		SELECT CASE 
			WHEN previous_purchases = 1 THEN 'New'
			WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
			ELSE 'Loyal'
			END AS customer_segment
		FROM customer_behaviour
	);		

SELECT customer_segment,COUNT(*) AS no_of_customers
FROM customer_type
GROUP BY 1;

--Q8) What are the top 3 most purchased products within each category?
--USIING CTAS AND WINDOWS FUNCTION

CREATE TABLE item_counts AS 
(
	SELECT category, 
		item_purchased,
		COUNT(customer_id) AS total_orders,
		ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS rank_items
	FROM customer_behaviour
	GROUP BY 1,2
);

SELECT rank_items, category, item_purchased, total_orders 
FROM item_counts
WHERE rank_items <=3;

--Q9)Are customers who are repeat buyers (more than 5 pervious purchases) also likely to subscribe ?

SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customer_behaviour
WHERE previous_purchases >5
GROUP BY 1

--Q10) What is the revenue contribution of each age group?

SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customer_behaviour
GROUP BY 1
ORDER BY 2 DESC;

